version: "3"
services:
  sql1:
    build: ./sql
    ports:
      - "1433:1433"
    volumes:
      - /home/circleci/repos:/opt/mssql/github
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=yourStrong(!)Password
    tty: true
    stdin_open: true
  sql2:
    build: ./sql
    ports:
      - "1434:1433"
    volumes:
      - /home/circleci/repos:/opt/mssql/github
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=yourStrong(!)Password
    tty: true
    stdin_open: true
  testb:
    build: ./client
    volumes:
      - /home/circleci/repos/:/opt/mssql/github
    tty: true
    stdin_open: true